quotes = [
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do Java developers wear glasses? Because they don't C#!",
    "Why do programmers prefer using the dark theme? Because light attracts bugs.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why was the computer cold? It left its Windows open.",
    "Why did the developer go broke? He lost his domain in a bet.",
    "Why do programmers hate nature? It has too many branches.",
    "Why don't programmers like to go outside? The sunlight causes too much glare.",
    "Why did the developer go to therapy? He had too many sessions with NullPointerExceptions.",
    "Why was the programming book sad? It had too many chapters on exceptions.",
    "Why did the programmer put his computer in the freezer? He wanted to break the ice.",
    "Why do programmers prefer cats over dogs? Cats have better exception handling.",
    "Why did the programmer storm out of the restaurant? The seating was arrayed wrong.",
    "Why did the programmer plant a tree? He wanted to create a branching structure.",
    "Why did the computer go to therapy? It had too many bytes of emotional baggage.",
    "Why was the code cold? It left its functions uncalled.",
    "Why did the programmer bring a ladder to the bar? He heard the drinks were on the house.",
    "Why do programmers prefer using the keyboard over the mouse? Because it has fewer clicks.",
    "Why did the programmer go to jail? He got caught trying to hack the mainframe.",
    "Why don't programmers like to gamble? They're afraid of getting bit by random bugs.",
    "Why did the programmer put his money in cryptocurrency? He wanted his assets to multiply.",
    "Why do programmers hate insects? They're always using bugs as stepping stones.",
    "Why did the programmer go swimming in the ocean? He wanted to test the waters of debugging.",
    "Why was the computer cold and lonely? It had too many unresponsive users.",
    "Why did the developer become a gardener? He wanted to cultivate his coding skills.",
    "Why don't programmers like coffee breaks? They can't handle the Java.",
    "Why did the programmer go broke buying new hardware? He had too much cache in hand.",
    "Why do programmers avoid parallel lines? They fear they might meet at an intersection.",
    "Why was the algorithm cold? It didn't have any recursion to keep it warm.",
    "Why did the programmer start a band? He wanted to use a lot of strings.",
    "Why do programmers prefer fiction? Reality has too many bugs.",
    "Why did the developer go fishing? He heard the bytes were biting.",
    "Why did the programmer bring a ladder to the bar? He heard the drinks were on the stack.",
    "Why do programmers dislike elevators? They can't stand closed loops.",
    "Why did the developer go broke? He invested all his money in NaN-currencies.",
    "Why did the programmer go to therapy? His code had too many issues.",
    "Why do programmers prefer low-fat diets? Because fat binaries are hard to digest.",
    "Why was the computer cold? It left its Windows open, so it caught a virus.",
    "Why did the developer go broke? He spent all his money on the latest frameworks.",
    "Why do programmers always carry a pencil? In case they need to draw a byte.",
    "Why did the programmer go to jail? He got caught using illegal characters.",
    "Why do programmers hate nature? It's full of recursion.",
    "Why did the programmer go broke? He lost all his inheritance in a merge conflict.",
    "Why do programmers avoid arguments? They don't like confrontation.",
    "Why was the code wet? It couldn't find its umbrella statement.",
    "Why did the programmer go broke? He spent all his money on virtual reality.",
    "Why do programmers like to sail? It helps them keep their code afloat.",
    "Why was the computer cold? It left its CAPS LOCK on.",
    "Why did the programmer go to therapy? He had too many deeply nested issues.",
    "Why do programmers prefer autumn? Fewer bugs are flying around.",
    "Why did the developer go broke? He tried to optimize his expenses but divided by zero.",
]
